Come-On-App/Come-On-Frontend

.eslintrc.json
package.json

- 개발의 일관성을 위해서 개발에 필요한 ESLint Ruls을 추가하였습니다.
- package에 추가정보를 기입하였습니다.
- 함수의 매개변수를 3개로 제한하였습니다.
- indent(인덴트, 들여쓰기) depth를 3이 넘지 않도록 구현하였습니다. 2까지만 허용합니다.
**예를 들어 while문 안에 if문이 있으면 들여쓰기는 2입니다.**
- 논리적으로 다른 블록은 한 줄 띄어 쓰도록 추가하였습니다.
- 함수와 다른 함수의 사이에는 공백이 필요하도록 추가하였습니다.
- 같은 할당문은 (e.g: var, let, const) 띄어쓰기를 허용하지 않습니다.
다음 문서를 참고하여 ESLint Ruls 설정을 하였습니다.
[ko.javascript.info](https://ko.javascript.info/coding-style)
- 신규 추가 입니다.
<br>
<br>
<hr>

🍕 [config] : ESLint Ruls 추가 & package.json 내용 추가 

---

.eslintrc.json
constants/Colors.ts
package-lock.json
package.json
types.tsx

- [Figma 참조 링크](https://www.figma.com/file/ViqLfX8QzqYfab2KU7PJyL/Come-on!-team-library?node-id=2031%3A2528&t=OWD7h27jvib9Ezdh-0) 
- 공통으로 사용되는 색상, 폰트 등을 설정하였습니다.
- 전역 색상
- 폰트 크기
- bold 속성 추가
- grayscale
- 현재 다크모드를 지원하지 않습니다.
- ESLint 제외 파일 목록을 추가하였습니다.
<br>
<br>
<hr>

🍕 [styles] : 전역 테마 색상 & 타입 설정

---

api/googleMap.ts
types/index.ts

1. 액션과 계산을 분리하였습니다.
2. 타입을 파일로 분리시켰습니다.
<br>
<br>
<hr>

🔨 Refactor : 구글 맵 API 로직 리팩토링

---

src/api/queryClient.ts
src/components/calendar/Calendar.tsx
src/components/calendar/DateModal.tsx
src/components/input/InputForm.tsx
src/components/member/MemberBox.tsx
src/features/socketSlice.ts
src/hooks/useMeeting.ts
src/hooks/useSocketMeeting.ts
src/hooks/useSubscribe.ts
src/navigation/index.tsx
src/screens/CreateMeeting.tsx
src/screens/MeetingRoom.tsx
src/screens/MeetingRoomCalendar.tsx
src/screens/meeting/detail/Member.tsx
src/screens/meeting/detail/date.tsx
src/screens/meeting/detail/index.tsx
src/types/index.ts
src/types/meeting.calendar.ts
src/types/navigation.ts
src/utils/image.ts
src/utils/promise.ts

- 기존의 코드를 병합했습니다.
- ☀️ Close : 코드 병합, 오류 수정
<br>
<br>
<hr>

🍕 [feature]: 코드 병합, 오류 수정

---

src/screens/CreateMeeting.tsx
src/screens/KakaoLoginView.tsx

- 
- 로그인 네이티브별 분리
- 스크롤 뷰 적용
-
<br>
<br>
<hr>

Feature tab two screen

---

src/components/button/KakaoLoginBtn.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/CustomCalendarTheme.tsx
src/components/calendar/DateModal.tsx
src/components/input/InputForm.tsx
src/components/input/InputImage.tsx
src/components/meetingCard/CardTop.tsx
src/components/member/MemberBox.tsx
src/components/myPage/MyPageLogoutButton.tsx
src/constants/themed.ts
src/features/meetingSlice.tsx
src/hooks/useAuth.ts
src/hooks/useMeeting.ts
src/hooks/useSubscribe.ts
src/navigation/index.tsx
src/screens/CreateMeeting.tsx
src/screens/CreateMeetingCalender.tsx
src/screens/LoginScreen.tsx
src/screens/MeetingRoomCalendar.tsx
src/screens/PeriodCalender.tsx
src/screens/SelectCalendar.tsx
src/screens/bottomTap/TabOneScreen.tsx
src/screens/meeting/detail/common.tsx
src/screens/meeting/detail/date.tsx
src/types/index.ts
src/types/navigation.ts
src/utils/image.ts

- 로그인 로직 수정
- expo WebBrowser 를 이용해 로그인 로직을 수정했습니다.
- 화면 사이즈에 맞지않는 캘린더 디자인을 수정했습니다.
<br>
<br>
<hr>

[Feature] 로그인 로직 수정, 리팩토링

---

src/api/meeting/members.ts
src/components/button/FlexButtons.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/ModalCalendar.tsx
src/navigation/index.tsx
src/screens/bottomTap/TabOneScreen.tsx
src/screens/meeting/create/CreateMeeting.tsx
src/screens/meeting/create/PeriodCalender.tsx
src/screens/meeting/detail/SelectCalendar.tsx
src/types/meeting.calendar.ts

- 모달 캘린더를 추가했습니다.
- - Calendar의 options 중 noListCalendar를 true로 주면 사용할 수 있습니다.
<br>
<br>
<hr>

🍕 [Feature] : 모달캘린더 추가

---

src/screens/meeting/create/PeriodCalender.tsx

🎨 Design : 캘린더 코드 리팩토링

---

src/components/calendar/Calendar.tsx
src/components/calendar/DateModal.tsx
src/components/calendar/ModalCalendar.tsx
src/components/calendar/PeriodArrowCalendar.tsx
src/screens/meeting/create/PeriodCalender.tsx
src/types/meeting.calendar.ts

- 캘린더 컴포넌트 분리
- 캘린더 Default 해당월이 제대로 렌더링 되지 않는 이슈 픽스
<br>
<br>
<hr>

🔨 Refactor : 캘린더 최적화

---

app.config.ts
eas.json
package.json
yarn.lock

- 재빌드, 재배포 없이 앱을 업데이트가 가능하게 추가하였습니다.
- 구성 환경을 환경 변수에 따라서 다르게 작업하도록 만들었습니다.
- EAS 구성과 추가 설정이 있습니다
<br>
<br>
<hr>

🍕 [Feature] : EAS Update Flow 추가 & 환경변수 구성  

---

app.config.ts
src/api/user/user.ts
src/components/button/CancelIconButton.tsx
src/hooks/query/useUserQuery.ts
src/hooks/useSubscribe.ts
src/screens/meeting/detail/index.tsx
src/screens/place/Select.tsx
src/types/api.user.ts
src/utils/fn.ts
src/utils/secureStore.ts

1. Cannot use the AuthSession proxy because the project full name is not defined. 에러 조치
2. 안드로이드 플랫폼 뒤로가기 액션 언락 버그 수정
3. 유저 조회 v2 API 적용
<br>
<br>
<hr>

🦊 Fix : 오류 수정

---

src/components/button/CancelButton.tsx
src/components/button/ConfirmButton.tsx
src/components/button/FlexButtons.tsx
src/components/button/GoogleLoginBtn.tsx
src/components/button/KakaoLoginBtn.tsx
src/constants/config.ts
src/screens/LoginScreen.tsx
src/screens/login/Apple.tsx
src/screens/settingScreen/IconTitle.tsx
src/screens/settingScreen/SettingScreen.tsx

- 회원탈퇴 모달창 추가
- 로그인 취소 시 indicator 계속됐던 문제 수정
- 로그인 문제 수정
-
<br>
<br>
<hr>

➕ Add : 회원탈퇴 모달창 추가

---

src/api/auth/auth.ts
src/screens/settingScreen/SettingScreen.tsx

- 로그인 시 재요청 안되는 이슈 해결
- 회원탈퇴 문구 추가
- 로그인 시 재요청 안되는 이슈 해결
- 회원탈퇴 문구 추가
-
<br>
<br>
<hr>

🖌️ Modify : 로그인 시 재요청 안되는 이슈 해결

---

src/api/auth/auth.ts
src/features/authSlice.ts
src/hooks/query/useMeetingQuery.ts
src/hooks/useAuth.ts
src/screens/meeting/detail/SelectCalendar.tsx
src/screens/settingScreen/SettingScreen.tsx

- v1 api v2로 업그레이드
-
-
<br>
<br>
<hr>

🍕 [Feature] : v1 api v2로 업그레이드

---

README.md
src/components/calendar/Calendar.tsx
src/screens/meeting/create/PeriodCalender.tsx

- 캘린더 날짜 스타일링 변경
- 사이즈 대응 안되는 스타일링 변경
-
<br>
<br>
<hr>

🍕 [newDev] : 캘린더 사이즈에 의해 디자인 변경되는 부분 제거

---

.gitignore
README.md
src/features/authSlice.ts
src/hooks/useAuth.ts
src/navigation/index.tsx

- 자동로그인 되도록 기능 수정
- 사용하지 않는 로그인관련 함수 삭제
<br>
<br>

🍕 [newDev] : 자동로그인 오류 해결및 로그인 로직 리팩터링

---

modules/app/mocks/handlers.ts
modules/app/navigation/config.tsx
modules/app/navigation/type.ts
modules/connection/api/v1/index.ts
modules/connection/api/v1/type.ts
modules/connection/components/MeetingJoinForm.tsx
modules/connection/components/button/CodeEntryButton.spec.tsx
modules/connection/components/button/CodeEntryButton.tsx
modules/connection/components/button/type.ts
modules/connection/components/description/CodeDescription.tsx
modules/connection/components/entranceInput/type.ts
modules/connection/components/type.ts
modules/connection/hooks/useMeetingJoinMutation.ts
modules/connection/mocks/handlers.ts
modules/connection/screen/EnterMeeting.spec.tsx
modules/connection/screen/EnterMeeting.tsx
modules/shared/components/description/Description.tsx
modules/shared/components/description/type.ts
modules/shared/components/input/CodeField.tsx
modules/shared/utils/haptics.ts

모임 입장 (#148) to 2.0(alpha) 

---

modules/post/components/detail/duration/votingStatus/voteButton/ConfirmMeetingDateButton.tsx
modules/post/components/detail/duration/votingStatus/voteButton/ToggleVoteButton.tsx
modules/post/components/detail/planner/customField/footer/SubmitButton.tsx
modules/post/screens/MeetingPostCreator.tsx

사용자 피드백 (햅틱 API) #182

---

eas.json
modules/post/components/invitation/code/field/style.ts
modules/shared/components/modal/style.ts

- 안드로이드 플랫폼 초대 코드 스타일링 이슈 수정
- 프리뷰 배포 타입 구성

Fix: style 수정

---

app.config.ts
modules/app/api/axiosInstance.ts
package.json
yarn.lock

- analytics
- crashlytics
- perf
- axios 요청/응답 로깅

Add: firebase 설정

---

jest/mock.setup.ts
modules/account/components/accountManagement/AccountManagement.tsx
modules/app/api/axiosInstance.ts
modules/app/api/interceptors/firebasePerf.ts
modules/app/navigation/RootNavigation.tsx
modules/connection/hooks/useMeetingJoinMutation.ts
modules/post/screens/MeetingPostCreator.tsx
modules/shared/logging/post.ts
modules/shared/logging/user.ts

- 스크린 tracking
- 모임 생성
- 모임 입장
- 회원 탈퇴
- 로직 개선
- 테스트 코드 모듈 일부 mock 처리

firebase logging 추가
